### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [chandrikadeb7/Face-Mask-Detection#92] opened 2021-01-15 04:45 UTC
## 📚 Documentation

To make README.md file beautiful and give credit to contributors
Like this
![image](https://user-images.githubusercontent.com/68433936/104682288-53b3f180-571a-11eb-89e0-7162eaf98b46.png)

**Comment by samir-0711** [comment] 2021-01-15 04:45
I would like to work on this.

**Comment by chandrikadeb7** [comment] 2021-01-16 09:10
Duplicate of issue #77

**Closed** 2021-01-17 15:54 UTC
Labels: documentation, duplicate
